# PID gains for the steer_bot_hardware_gazebo plugin.
gains:
  back_right_wheel_joint:
    p: 100000.0
    d: 10.0
    i: 0.50
    i_clamp: 3.0
  back_left_wheel_joint:
    p: 100000.0
    d: 10.0
    i: 0.50
    i_clamp: 3.0

