<?xml version="1.0"?>
<robot name="constants" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Body properties -->
    <xacro:property name="body_mass" value="2.5"/>
    <xacro:property name="body_length" value="0.14"/>
    <xacro:property name="body_width" value="0.05"/>
    <xacro:property name="body_height" value="0.04"/>

    <!-- Wheels properties -->
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_radius" value="0.01"/>
    <xacro:property name="wheel_width" value="0.006"/>
    <xacro:property name="wheel_separation" value="0.047"/>

    <!-- Distances from Body to Wheels -->
    <xacro:property name="fb_separation" value="0.286"/>
    <xacro:property name="lr_separation" value="0.304"/>
    <xacro:property name="height_to_wheel" value="-0.1135"/>

    <!-- Wheel dimensions -->
    <xacro:property name="wheel_radius" value="0.0635"/>
    <xacro:property name="thickness" value="0.1016"/>

    <!-- Axle Positions: Check with Mech Team, currently made up -->
    <xacro:property name="axel_offset" value="0.05"/>
    <xacro:property name="steer_offset" value="0.02"/> 

    <!-- Steer dimensions: Check with Mech Team, currently made up -->
    <xacro:property name="steer_radius" value="0.05"/> 
    <xacro:property name="steer_thickness" value="0.02"/>
    <xacro:property name="steer_mass" value="1.0"/>

    <!-- Steer properties: Check with Mech Team, currently made up -->
    <xacro:property name="steer_velocity" value="5.0"/> 
    <xacro:property name="steer_effort" value="10.0"/>
    <xacro:property name="steer_limit" value="${90.0 * pi/180}"/>

    <!-- LIDAR -->
    <xacro:property name="laser_visualize" value="false"/>
    <xacro:property name="laser_update_rate" value="10"/>
    <xacro:property name="laser_field_of_view" value="270"/>
    <xacro:property name="laser_min_range" value="0.06"/>
    <xacro:property name="laser_max_range" value="4.095"/>

    <!-- STEREO CAMERA -->
    <xacro:property name="camera_mass" value="0.1587573"/>
    <xacro:property name="camera_length" value="0.175"/>
    <xacro:property name="camera_width" value="0.03"/>
    <xacro:property name="camera_height" value="0.033"/>
    <xacro:property name="camera_pitch" value="${5 * pi/180}"/>

    <xacro:property name="camera_update_rate" value="30"/>
    <xacro:property name="camera_hfov" value="${90 * pi/180}"/>
    <xacro:property name="stereo_offset" value="${camera_length / 2.0}"/>    <!-- Distance between left and right cameras -->
    <xacro:property name="image_width" value="1920"/>
    <xacro:property name="image_height" value="1080"/>
    <xacro:property name="image_format" value="R8G8B8"/>

    <xacro:property name="camera_ns" value="camera/camera_node"/>  <!-- Use a name representative of the camera being used -->
    <xacro:property name="always_on" value="true"/>
    <xacro:property name="image_topicName" value="image_raw_color"/>
    <xacro:property name="image_info_topicName" value="camera_info"/>
    <xacro:property name="depth_topicName" value="depth/image_raw"/>
    <xacro:property name="depth_info_topicName" value="depth/camera_info"/>
    <xacro:property name="pointcloud_topicName" value="pointcloud"/>
    <xacro:property name="camera_left_optical_frame" value="camera_left_link_optical"/>
    
    <!-- IMU -->
    <xacro:property name="imu_update_rate" value="128"/>

</robot>
