<?xml version="1.0"?>
<robot name="constants" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Distances from Body to Wheels -->
    <xacro:property name="fb_separation" value="0.286"/>
    <xacro:property name="lr_separation" value="0.304"/>
    <xacro:property name="height_to_wheel" value="-0.1135"/>
    <xacro:property name="front_wheel" value="${fb_separation/2}"/>
</robot>

