<?xml version="1.0"?>
<robot name="cybertruck" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>
    <xacro:include filename="$(find description)/urdf/plugins.gazebo.xacro"/>

    <link name="base_link"/>

    <!-- Body -->
    <link name="body_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/StampedeBody.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://description/urdf/meshes/StampedeBody.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <inertial>
            <xacro:body_inertia/>
        </inertial>
    </link>

    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
    </joint>

    <!-- Wheels -->
    <xacro:include filename="$(find description)/urdf/wheels.urdf.xacro"/>

     <!-- LIDAR -->
    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.03 0.03" />
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="body_link"/>
        <child link="lidar_link"/>
        <origin xyz="${fb_separation/2} 0 ${-height_to_wheel/2}" rpy="0 0 0"/>
    </joint>

     <!-- IMU -->
    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.03 0.03" />
            </geometry>
            <material name="Cyan">
                <color rgba="0 0.0 1.0 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="body_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 ${-height_to_wheel}" rpy="0 0 0"/>
    </joint>

    <!-- ZED Camera -->
    <link name="${tf_prefix}/camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </collision>
        <inertial>
            <xacro:box_inertia mass="${camera_mass}" length="${camera_length}" width="${camera_width}" height="${camera_height}"/>
            <mass value="${camera_mass}"/>
        </inertial>
    </link>
    <joint name="${tf_prefix}/camera_joint" type="fixed">
        <origin xyz="${stand_length/2 - camera_width} 0 ${camera_height / 2.0}" rpy="0 ${camera_pitch} 0"/>
        <parent link="${tf_prefix}/stand_link"/>
        <child link="${tf_prefix}/camera_link"/>
    </joint>
</robot>
