<?xml version="1.0"?>
<robot name="photon" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--
Robot model taken from http://wiki.ros.org/pr2_mechanism/Tutorials/SImple%20URDF-Controller%20Example
-->
    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>
    <xacro:include filename="$(find description)/urdf/photon_wheels.urdf.xacro"/>
    <xacro:include filename="$(find description)/urdf/plugins.gazebo.xacro"/>

    <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

    <!-- Links: inertial,visual,collision -->
    <link name="base_link">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://description/urdf/meshes/Body.STL" scale="0.001 0.001 0.001"/>
        </geometry>
        </visual>

        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://description/urdf/meshes/Body.STL" scale="0.001 0.001 0.001"/>
        </geometry>
        </collision>

        <inertial>
        <xacro:body_inertia/>
        </inertial>
    </link>

    <!-- joints for ackermann_steering_controller -->
    <xacro:front_steer name="front" parent="base" length="${fb_separation}" 
        steer_height="${wheel_radius+steer_offset}"/>
    <xacro:rear_wheel name="rear" parent="base">
        <origin xyz="${-fb_separation/2} 0 ${height_to_wheel}" rpy="${-90 * deg_to_rad} 0 0"/>
    </xacro:rear_wheel>

    <!-- Wheels -->
    <xacro:front_wheel_lr name="front_right" parent="base" length="${fb_separation}" 
        width="${lr_separation}" right_left="1" steer_height="${wheel_radius+steer_offset}"/>
    <xacro:front_wheel_lr name="front_left" parent="base" length="${fb_separation}" 
        width="${lr_separation}" right_left="-1" steer_height="${wheel_radius+steer_offset}"/>
    <xacro:rear_wheel_lr name="rear_right" parent="base">
        <origin xyz="${-fb_separation/2} ${lr_separation/2} ${height_to_wheel}" rpy="0 0 0"/>
    </xacro:rear_wheel_lr>
    <xacro:rear_wheel_lr name="rear_left" parent="base">
        <origin xyz="${-fb_separation/2} ${-1*(lr_separation/2)} ${height_to_wheel}" rpy="0 0 0"/>
    </xacro:rear_wheel_lr>

    <!-- Colour -->
    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>
</robot>

