<?xml version="1.0"?>
<robot name="plugins" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Constants -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>

    <!-- LIDAR -->
    <gazebo reference="scan_link">
        <sensor type="ray" name="gpu_hokuyo_sensor">
            <pose>0 0 0 0 0 0</pose>
            <!-- TODO: Change values to actual lidar values-->
            <visualize>${laser_visualize}</visualize>
            <update_rate>${laser_update_rate}</update_rate> 
            <ray>
                <scan>
                    <horizontal>
                        <samples>1080</samples>
                        <resolution>1</resolution>
                        <min_angle>${-0.5*laser_field_of_view*pi/180}</min_angle>
                        <max_angle>${0.5*laser_field_of_view*pi/180}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${laser_min_range}</min>
                    <max>${laser_max_range}</max>
                    <resolution>${0.36* pi/180}</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>${0.01/3}</stddev>
                </noise>
            </ray>

            <plugin name="gazebo_ros_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>scan</topicName>
                <frameName>scan_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <!-- Differential Drive Controller -->
    <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <legacyMode>false</legacyMode>
            <rosDebugLevel>na</rosDebugLevel>

            <!-- Plugin update rate (Hz) -->
            <updateRate>30</updateRate>
            
            <!-- Name of joints connecting to wheels -->
            <leftJoint>front_left_wheel_joint</leftJoint>
            <rightJoint>front_right_wheel_joint</rightJoint>

            <!-- Wheel properties -->
            <wheelSeparation>${lr_separation}</wheelSeparation>
            <wheelDiameter>${2.0 * height_to_wheel}</wheelDiameter>
            <wheelAcceleration>0</wheelAcceleration>
            <wheelTorque>5</wheelTorque>


            <commandTopic>cmd_vel</commandTopic>

            <!-- Odometry -->
            <odometrySource>encoder</odometrySource>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_link</robotBaseFrame>

            <!-- TF frames -->
            <publishTf>true</publishTf>
            <publishOdomTF>true</publishOdomTF>

            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>true</publishWheelJointState>
        </plugin>
    </gazebo>

    <!-- Transmission-->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
    </gazebo>
</robot>
