<?xml version="1.0"?>
<robot name="wheels" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Includes -->
    <xacro:include filename="$(find description)/urdf/constants.xacro"/>
    <xacro:include filename="$(find description)/urdf/inertias.xacro"/>

    <!-- TODO: see if virtual objects can be invisible and have small masses (as to not affect Photon in anyway other than enable ackermann steering) -->

    <!-- MACRO -->

    <xacro:property name="steer_height" value="${wheel_radius + steer_offset}"/>

    <!-- Steer macro -->
    <xacro:macro name="Steer" params="name steer_limit *origin">
        <!-- Steer link -->
        <link name="${name}_steer_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
                </geometry>
                <material name="Yellow">
                    <color rgba="1.0 1.0 0.0 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${steer_radius}" length="${steer_thickness}"/>
                </geometry>
            </collision>

            <inertial>
                <xacro:cylinder_inertia mass="${steer_mass}" radius="${steer_radius}" length="${steer_thickness}"/>
            </inertial>
        </link>

        <!-- Steer joint -->
        <joint name="${name}_steer_joint" type="revolute">
            <parent link="body_link"/>
            <child link="${name}_steer_link"/>
            <xacro:insert_block name="origin"/>
            <axis xyz="0 0 1"/>
            <limit effort="${steer_effort}" lower="-${steer_limit}" upper="${steer_limit}" velocity="${steer_velocity}"/>
        </joint>

        <!-- Transmission -->
        <transmission name="${name}_steer_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${name}_steer_joint_motor">
                <mechanicalReduction>1</mechanicalReduction>
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </actuator>
            <joint name="${name}_steer_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>

    <!-- Wheel macro -->
    <xacro:macro name="Wheel" params="fb lr *parent *origin">
        <!-- Wheel link -->
        <link name="${fb}_${lr}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://description/urdf/meshes/Wheels.STL" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://description/urdf/meshes/Wheels.STL" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>

            <inertial>
                <xacro:wheel_inertia/>
            </inertial>
        </link>

        <!-- Wheel joint -->
        <joint name="${fb}_${lr}_wheel_joint" type="continuous">
            <xacro:insert_block name="parent"/>
            <child link="${fb}_${lr}_wheel_link"/>
            <xacro:insert_block name="origin"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- Transmission -->
        <transmission name="${fb}_${lr}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${fb}_${lr}_wheel_joint_motor">
                <mechanicalReduction>1</mechanicalReduction>
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </actuator>
            <joint name="${fb}_${lr}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>

    <!-- INSTANTIATION -->

    <!-- Instantiate Front Steers (Ackermann Steering) -->
    <xacro:Steer name="front" steer_limit="${180.0 * pi/180}">
        <origin xyz="${fb_separation/2} 0 ${steer_height}" rpy="0 0 0"/>
    </xacro:Steer>
    
    <xacro:Steer name="front_left" steer_limit="${steer_limit}">
        <origin xyz="${fb_separation/2} -${lr_separation/2} ${steer_height}" rpy="0 0 0"/>
    </xacro:Steer>
    <xacro:Steer name="front_right" steer_limit="${steer_limit}">
        <origin xyz="${fb_separation/2} ${lr_separation/2} ${steer_height}" rpy="0 0 0"/>
    </xacro:Steer>

    <!-- Instantiate Virtual Rear Wheel (Ackermann Steering) -->
    <link name="virtual_rear_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${thickness}"/>
            </geometry>
            <material name="Yellow">
                <color rgba="1.0 1.0 0.0 1.0"/>
            </material>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${thickness}"/>
            </geometry>
        </collision>

        <inertial>
            <xacro:wheel_inertia/>
        </inertial>
    </link>

    <joint name="virtual_rear_wheel_joint" type="continuous">
        <parent link="body_link"/>
        <child link="virtual_rear_wheel_link"/>
        <origin xyz="-${fb_separation/2} 0 ${height_to_wheel}" rpy="${-90 * pi/180} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <transmission name="virtual_rear_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="virtual_rear_wheel_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </actuator>
        <joint name="virtual_rear_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>

    <!-- Instantiate Physical Wheels -->
    <xacro:Wheel fb="front" lr="left">
        <parent link="front_left_steer_link"/>
        <origin xyz="0 0 ${height_to_wheel - steer_height}" rpy="0 0 0"/>
    </xacro:Wheel>
    <xacro:Wheel fb="front" lr="right">
        <parent link="front_right_steer_link"/>
        <origin xyz="0 0 ${height_to_wheel - steer_height}" rpy="0 0 0"/>
    </xacro:Wheel>

    <xacro:Wheel fb="back" lr="left">
        <parent link="body_link"/>
        <origin xyz="-${fb_separation/2} -${lr_separation/2} ${height_to_wheel}" rpy="0 0 0"/>
    </xacro:Wheel>
    <xacro:Wheel fb="back" lr="right">
        <parent link="body_link"/>
        <origin xyz="-${fb_separation/2} ${lr_separation/2} ${height_to_wheel}" rpy="0 0 0"/>
    </xacro:Wheel>

</robot>
